### ISSUE TITLE
Able to get 0.1.0 on SPM but not 0.2.0 (xcode 13.2.1)

### ISSUE THREAD

**Issue by bfongbfong** [TizianoCoroneo/Deeplink#1]
**Describe the bug**
I am able to get version 0.1.0 on SPM, but not version 0.2.0

Dependencies could not be resolved because no versions of 'Deeplink' match the requirement 0.2.0 and root depends on 'Deeplink' 0.2.0

**Comment by TizianoCoroneo** [comment]
Hello 👋 
The latest version of the library is 0.1.1, I fixed the issue in the README 😄 
The following line should work:
```swift
.package(url: "https://github.com/TizianoCoroneo/Deeplink", .upToNextMinor(from: "0.1.1"))
```

Thanks for the report!
